# This is a basic workflow to help you get started with Actions

name: Reusable- Generate Alert Report

# Controls when the workflow will run
on:  
  workflow_call:
    inputs:
      PRACTICE:
        type: string
        required: true
        default: DevOps

jobs:       
  runReport:
    runs-on: ubuntu-latest    
    steps:    
      - name: Generate Report            
        run: |
          echo Hello, world!
          echo "input-PRACTICE: ${inputs.PRACTICE}"
