name: Generate Report - Schedule - Alternate Fridays

# Controls when the workflow will run
on:  
  workflow_dispatch:
  schedule:
    - cron: 26 10 * * 4

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-week-number:
    runs-on: ubuntu-latest
    outputs:
      weekNumber: ${{ steps.getWeekNumber.outputs.result }}
    steps:
      - name: Get Week Number from epoch
        id: getWeekNumber
        uses: actions/github-script@v6
        with:          
          script: |
            let jsTime = new Date().getTime();
            let weekNumber = Math.floor ((jsTime + 345_600_000) / 604_800_000);
            console.log(`weekNumber: ${weekNumber}`)
            isEven = (weekNumber%2 == 0)
            console.log(`isEven: ${isEven}`)
            return isEven;
  
  job2:
    uses: ./.github/workflows/reusable.yml
    needs: get-week-number
    if: ${{ needs.get-week-number.outputs.weekNumber == 'true' }}
    with:
      PRACTICE: "AWS"
    secrets: inherit
