# This is a basic workflow to help you get started with Actions

name: Generate Report Manual Trigger

# Controls when the workflow will run
on:  
  workflow_dispatch:
    inputs:
      PRACTICE:
        type: choice
        required: true
        default: DevOps
        options:
        - DevOps
        - QE
        - AWS


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generateReport:
    uses: ./.github/workflows/reusable.yml
    with:
      PRACTICE: ${{ inputs.PRACTICE }}
    secrets: inherit
