# This is a basic workflow to help you get started with Actions

name: Run on Alternate Fridays

# Controls when the workflow will run
on:
  
  workflow_dispatch:
  schedule:
    - cron: 2 4 * * 3 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  getWeekNumber:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      weekNumber: ${{ steps.get-week-number.outputs.result }}
      
    steps:
      - name: Get Week Number from epoch
        id: get-week-number
        uses: actions/github-script@v6
        with:          
          script: |
            let jsTime = new Date().getTime();
            let weekNumber = Math.floor ((jsTime + 345_600_000) / 604_800_000);
            console.log(`weekNumber: ${weekNumber}`)
            isEven = (weekNumber%2 == 0)
            console.log(`isEven: ${isEven}`)
            return isEven;
            
  runReport:
    runs-on: ubuntu-latest
    needs: getWeekNumber
    if: ${{ needs.getWeekNumber.outputs.weekNumber == 'true' }}
    steps:    
      - name: Generate Report            
        run: |
          echo Hello, world!
          echo ${{ needs.getWeekNumber.outputs.weekNumber }}

    
