name: Generate Report - Schedule - Alternate Fridays

# Controls when the workflow will run
on:  
  workflow_dispatch:
  schedule:
    - cron: 12 13 * * 3

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "Job1"
  
  job2:
    uses: ./.github/workflows/reusable.yml
    with:
      PRACTICE: "AWS"
    secrets: inherit
