# This is a basic workflow to help you get started with Actions

name: Run on Alternate Fridays

# Controls when the workflow will run
on:
  
  workflow_dispatch:
  schedule:
    - cron: 43 2 * * 3 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Get Week Number from epoch
        id: get-week-number
        uses: actions/github-script@v6
        with:          
          script: |
            let jsTime = new Date().getTime();
            let weekNumber = Math.floor ((jsTime + 345_600_000) / 604_800_000);
            console.log(`weekNumbe: ${weekNumber}`)                        

      # Runs a single command using the runners shell
      - name: Run a one-line script
        if: ${{ (steps.set-result.outputs.result)%2 == 0 }}
        run: echo Hello, world!

    
